name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_release:
    name: build and push release
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: setup
      run: |
        wget https://github.com/pkghaus/zola-debian/releases/download/v0.23.3-1/zola_0.23.3-1_amd64_trixie.deb
        sudo dpkg -i zola_0.23.3-1_amd64_trixie.deb

    - uses: actions/setup-node@v3
      with:
        node-version: 20.20.2

    - name: build
      run: |
        npm i
        npm run build

    - name: push to s3, clear cloudfront
      if: github.ref_name=='main'
      run: |
        export AWS_ACCESS_KEY_ID=${{secrets.S3_ACCESS_KEY_ID}}
        export AWS_SECRET_ACCESS_KEY=${{secrets.S3_ACCESS_KEY}}
        export AWS_DEFAULT_REGION=us-west-2

        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install --update

        aws s3 cp public s3://n0.computer/ --recursive
        aws cloudfront create-invalidation --distribution-id ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}} --paths /*
